### ISSUE TITLE
Deploy error and syntax error in variables

### ISSUE THREAD

**Issue by aitormendez** [2kloc/trellis-monit#1]
Hi, I'm trying to deploy role to server. I can't do it:

```
ERROR! the role '2kloc.trellis-monit' was not found in /Volumes/B/Documentos/trellis2/ansible/roles:/Volumes/B/Documentos/trellis2/ansible/vendor/roles:/Volumes/B/Documentos/trellis2/ansible

The error appears to have been in '/Volumes/B/Documentos/trellis2/ansible/server.yml': line 43, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - { role: wordpress-setup, tags: [wordpress, wordpress-setup, letsencrypt] }
    - { role: 2kloc.trellis-monit, tags: [monit] }
      ^ here
```

I can deploy role just changing server role line to: 

`- { role: trellis-monit, tags: [monit] }`

**Is it right?**

Also, I get a syntax error in the first variable found in monit/monit.conf.j2:

```
# Check service every X seconds
monit_daemon: 120;
```
The error is: /etc/monit/conf.d/monit.conf:2: Error: syntax error 'monit_daemon'

**How can be it fixed?**

**Comment by alexandcote** [comment]
Hi @aitormendez, 

You are right, the correct syntax is : 
```
- { role: trellis-monit, tags: [monit] }
```
I will fix the documentation 
___

For your variable error, the `monit` folder should contain monit tasks.

### Example
```
monit
│   nginx.conf.j2
│   php7.1-fpm.conf.j2
│   ...
```

The `nginx.conf.j2` look like
```
check process nginx with pidfile /var/run/nginx.pid
    start program = "/etc/init.d/nginx start"
    stop program  = "/etc/init.d/nginx stop"
    group www-data
    if failed host 127.0.0.1 port 80 then restart
```

If you want to redefine default variable you need to add the variables into: `group_vars/all/main.yml` or `group_vars/<ENV>/main.yml` 

For my servers, I only changed these variables:

```
# group_vars/all/main.yml
...
monit_smtp: true
monit_smtp_sysadmin_email: my@email.com
```
